on:
  push:
    branches:
      - alpha

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.package_version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install
      - name: Run start script
        run: npm run start
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: index
          path: index.json

  release:
    needs: [build]
    runs-on: ubuntu-latest
    if: needs.build.outputs.version != ''
    steps:
      - uses: actions/checkout@v3
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: index.json
